IF OBJECT_ID('InsertarUsuario') IS NOT NULL
BEGIN 
DROP PROC InsertarUsuario 
END
GO
CREATE PROCEDURE InsertarUsuario(
	   @ID_USER int,
	   @FIRST_NAME varchar(15),
	   @SECOND_NAME	varchar(15),
	   @LAST_NAME varchar(15),
	   @LAST_NAME2 varchar(15),
	   @USER_ADDRESS varchar(30),
	   @ID_COMUNIDAD int)
AS
BEGIN
INSERT INTO USUARIO (
	   ID_USER,
	   FIRST_NAME,
	   SECOND_NAME,
	   LAST_NAME,
	   LAST_NAME2,
	   USER_ADDRESS,
	   ID_COMUNIDAD)
    VALUES (
	   @ID_USER,
	   @FIRST_NAME,
	   @SECOND_NAME,
	   @LAST_NAME,
	   @LAST_NAME2,
	   @USER_ADDRESS,
	   @ID_COMUNIDAD);


SET @ID_USER = SCOPE_IDENTITY()
END
GO
IF OBJECT_ID('InsertarProducto') IS NOT NULL
BEGIN 
DROP PROC InsertarProducto 
END
GO
CREATE PROCEDURE InsertarProducto(
	   @ID_PRODUCTO int,
	   @P_NAME varchar(20),
	   @DESCRIPCION	varchar(20),
	   @OTHER_DETAILS varchar(20),
	   @ID_COMUNIDAD int)
AS
BEGIN
INSERT INTO PRODUCTO(
	   ID_PRODUCTO,
	   P_NAME,
	   DESCRIPCION,
	   OTHER_DETAILS,
	   ID_COMUNIDAD)
    VALUES (
	   @ID_PRODUCTO,
	   @P_NAME,
	   @DESCRIPCION,
	   @OTHER_DETAILS,
	   @ID_COMUNIDAD);

SET @ID_PRODUCTO = SCOPE_IDENTITY()

--SELECT 
--	   P_NAME = @P_NAME,
--	   DESCRIPCION = @DESCRIPCION,
--	   OTHER_DETAILS= @OTHER_DETAILS,
--	   ID_COMUNIDAD = @ID_COMUNIDAD
--FROM PRODUCTO 
--WHERE  ID_PRODUCTO = @ID_PRODUCTO
END
GO

IF OBJECT_ID('InsertarComunidad') IS NOT NULL
BEGIN 
DROP PROC InsertarComunidad 
END
GO
CREATE PROCEDURE InsertarComunidad(
	   @ID_COMUNIDAD int,
	   @C_NAME varchar(20),
	   @DEPARTAMENTO varchar(20),
	   @OTHER_DETAILS varchar(20),
	   @CAP_INSTALADA varchar(20),
	   @ID_PRODUCTO int)
	 
AS
BEGIN
INSERT INTO COMUNIDAD(
	   ID_COMUNIDAD,
	   C_NAME,
	   DEPARTAMENTO,
	   OTHER_DETAILS,
	   CAP_INSTALADA,
	   ID_PRODUCTO)
    VALUES (
	   @ID_COMUNIDAD,
	   @C_NAME,
	   @DEPARTAMENTO,
	   @OTHER_DETAILS,
	   @CAP_INSTALADA,
	   @ID_PRODUCTO)

SET @ID_COMUNIDAD = SCOPE_IDENTITY()

--SELECT 
--	   C_NAME = @C_NAME,
--	   DEPARTAMENTO = @DEPARTAMENTO,
--	   OTHER_DETAILS= @OTHER_DETAILS,
--	   CAP_INSTALADA = @CAP_INSTALADA,
--	   ID_PRODUCTO = @ID_PRODUCTO
--FROM COMUNIDAD 
--WHERE  ID_COMUNIDAD = @ID_COMUNIDAD
END
GO

IF OBJECT_ID('InsertarComunidad') IS NOT NULL
BEGIN 
DROP PROC InsertarComunidad 
END
GO
CREATE PROCEDURE InsertarAlmacen
	   @ID_ALMACEN int,
	   @NOMBRE varchar(20),
	   @DESCRIPCION varchar(20)
AS
BEGIN
INSERT INTO ALMACEN (
	   ID_ALMACEN,
	   NOMBRE,
	   DESCRIPCION)
    VALUES (
	   @ID_ALMACEN,
	   @NOMBRE,
	   @DESCRIPCION)

SET @ID_ALMACEN = SCOPE_IDENTITY()

--SELECT 
--	   NOMBRE = @NOMBRE,
--	   DESCRIPCION = @DESCRIPCION
--FROM ALMACEN 
--WHERE  ID_ALMACEN = @ID_ALMACEN
END
GO

IF OBJECT_ID('InsertarComunidad') IS NOT NULL
BEGIN 
DROP PROC InsertarComunidad 
END
GO
CREATE PROCEDURE InsertarCOS(
	   @ID_CLASS int,
	   @DESCRIP	varchar(20),
	   @OTHER_DETAILS varchar(20),
	   @TEL_NUMBER int)
	 
AS
BEGIN
INSERT INTO CLASS(
	   ID_CLASS,
	   DESCRIP,
	   OTHER_DETAILS,
	   TEL_NUMBER)
    VALUES (
	   @ID_CLASS,
	   @DESCRIP,
	   @OTHER_DETAILS,
	   @TEL_NUMBER);

SET @ID_CLASS = SCOPE_IDENTITY()

--SELECT
--	   DESCRIP = @DESCRIP,
--	   OTHER_DETAILS= @OTHER_DETAILS,
--	   TEL_NUMBER = @TEL_NUMBER
--FROM CLASS 
--WHERE  ID_CLASS = @ID_CLASS
END
GO

IF OBJECT_ID('InsertarMovimiento') IS NOT NULL
BEGIN 
DROP PROC InsertarMovimiento 
END
GO
CREATE PROCEDURE InsertarMovimiento(
	   @FECHA_INGRESO date,
	   @OTHER_DETAILS varchar(20),
	   @FECHA_EGRESO date,
	   @ESTADO varchar(20),
	   @ID_PRODUCTO int)
	 
AS
BEGIN
INSERT INTO MOVIMIENTO(
	   FECHA_INGRESO,
	   OTHER_DETAILS,
	   FECHA_EGRESO,
	   ESTADO,
	   ID_PRODUCTO)
    VALUES (
	   @FECHA_INGRESO,
	   @OTHER_DETAILS,
	   @FECHA_EGRESO,
	   @ESTADO,
	   @ID_PRODUCTO);
END
GO

IF OBJECT_ID('InsertarTelefono') IS NOT NULL
BEGIN 
DROP PROC InsertarTelefono 
END
GO
CREATE PROCEDURE InsertarTelefono(
	   @TEL_NUMBER int,
	   @CKTO varchar(8),
	   @PAR_INTERNO int,
	   @PAR_EXTERNO int,
	   @ID_USER int)
	 
AS
BEGIN
INSERT INTO TELEFONO(
	   TEL_NUMBER,
	   CKTO,
	   PAR_INTERNO,
	   PAR_EXTERNO,
	   ID_USER)
    VALUES (
	   @TEL_NUMBER,
	   @CKTO,
	   @PAR_INTERNO,
	   @PAR_EXTERNO,
	   @ID_USER)

SET @TEL_NUMBER= SCOPE_IDENTITY()

--SELECT 
--	   CKTO = @CKTO,
--	   PAR_INTERNO = @PAR_INTERNO,
--	   PAR_EXTERNO= @PAR_EXTERNO,
--	   ID_USER = @ID_USER
--FROM TELEFONO 
--WHERE  TEL_NUMBER = @TEL_NUMBER
END
GO