--Procedimiento para INSERTAR usuario
CREATE PROCEDURE ADD_USUARIO(
	
	@ID INT, 
	@FNAME VARCHAR(15), 
	@SNAME VARCHAR(15), 
	@LNAME VARCHAR(15), 
	@LNAME2 VARCHAR(15), 
	@DIRECCION VARCHAR(30), 
	@OTHER_DETAILS VARCHAR(50), 
	@COMUNIDAD INT)
	as
	INSERT into  USUARIO (ID_USER, FIRST_NAME, SECOND_NAME, LAST_NAME, LAST_NAME2, USER_ADDRESS, OTHER_DETAILS, ID_COMUNIDAD)
	VALUES(@ID,@FNAME,@SNAME,@LNAME,@LNAME2, @DIRECCION, @OTHER_DETAILS, @COMUNIDAD);

--Procedimiento para UPDATE usuario
create procedure UPD_USUARIO(
	@ID INT, 
	@FNAME VARCHAR(15), 
	@SNAME VARCHAR(15), 
	@LNAME VARCHAR(15), 
	@LNAME2 VARCHAR(15), 
	@DIRECCION VARCHAR(30), 
	@OTHER_DETAILS VARCHAR(50), 
	@COMUNIDAD INT)
as
update dbo.USUARIO set
	FIRST_NAME=@FNAME, 
	SECOND_NAME=@SNAME,
	LAST_NAME=@LNAME,
	LAST_NAME2=@LNAME2, 
	USER_ADDRESS=@DIRECCION,
	OTHER_DETAILS=@OTHER_DETAILS,
	ID_COMUNIDAD=@COMUNIDAD
	where
		ID_USER=@ID
go

--Procedimiento de ELIMINAR cliente
create procedure DEL_USUARIO(
@ID int)
as
delete from dbo.USUARIO
where
ID_USER=@ID
go

